### ISSUE TITLE
CommandMergeTinyV2 doesn't like members with the same name but different descriptors

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/stitch#28]
Proguard creates these when obfuscating, but it throws an exception when you try to merge two mappings by the obf names:
```
java.lang.IllegalStateException: Duplicate key net.fabricmc.stitch.commands.tinyv2.TinyField@4623e502
	at net.fabricmc.stitch.commands.tinyv2.TinyClass.mapFieldsByFirstNamespace(TinyClass.java:63)
	at net.fabricmc.stitch.commands.tinyv2.CommandMergeTinyV2.mergeClasses(CommandMergeTinyV2.java:190)
	at net.fabricmc.stitch.commands.tinyv2.CommandMergeTinyV2.lambda$merge$0(CommandMergeTinyV2.java:140)
	at net.fabricmc.stitch.commands.tinyv2.CommandMergeTinyV2.map(CommandMergeTinyV2.java:304)
	at net.fabricmc.stitch.commands.tinyv2.CommandMergeTinyV2.merge(CommandMergeTinyV2.java:134)
	at net.fabricmc.stitch.commands.tinyv2.CommandMergeTinyV2.run(CommandMergeTinyV2.java:118)
```

**Comment by natanfudge** [comment]
Concern
